---
# Tmux role: ensure tmux is installed and configured

- name: Install tmux (Debian/Ubuntu)
  apt:
    name: tmux
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Install tmux (macOS)
  homebrew:
    name: tmux
    state: present
  become: yes
  become_user: "{{ sudo_user }}"
  become_method: su
  when: ansible_facts['os_family'] == "Darwin"

- name: Create tmux plugin directory
  file:
    path: "{{ ansible_facts['user_dir'] }}/.tmux/plugins/tpm"
    state: directory
    mode: '0755'

- name: Clone TPM (Tmux Plugin Manager)
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_facts['user_dir'] }}/.tmux/plugins/tpm"
    depth: 1
  ignore_errors: yes
